services:
  postgres:
    container_name: db
    image: postgres:alpine
    ports:
      - '5432:5432'
    volumes:
      - /data/postgres:/data/postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=nestjs-auth

  redis:
    container_name: cache
    image: redis:alpine
    ports:
      - 6379:6379

  mail:
    container_name: mail
    image: jijiechen/papercut:latest
    ports:
      - 25:25
      - 37408:37408
